server:
  port: 8082   # different from auth-service

jwt:
  secret: oenfoernfoienfondwofnwodfnowjnfijwqenfJ
  expiration: 86400000

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/sms_auth_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Boss@8055
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # IMPORTANT difference
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
